### ISSUE TITLE
国内Angular安装问题  ng install 一直失败

### ISSUE THREAD

**Issue by heyrdaxm** [ng-docs/ng-docs.github.io#7]
各位好！
目前我遇到的问题如下：
已经通过node.js安装了npm。
然后安装TYPESCRIPT命令成功。
同样通过NPM安装了Angular CRI：
npm install -g @angular/cli 
安装完成后得到版本如下：
Angular CLI: 6.2.2
Node: 8.12.0
OS: win32 x64
Angular:
...
然后install的时候有尝试 先指定cnpm到淘宝节点，但还是报错。报错信息如下：
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\Projects\Angular\ag2\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\Projects\Angular\ag2\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at E:\Projects\Angular\ag2\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Projects\\Angular\\ag2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\Projects\Angular\ag2\node_modules\node-sass
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

请问Angular安装跟python还有关？没有看到官网上有相关信息啊？

**Comment by asnowwolf** [comment]
其实并不是 Angular 本身依赖它，是因为Angular CLI 中的 node-sass 是原生库，它的二进制文件放在 aws 上。如果被墙了下载不下来，就会尝试从源码编译，这时候就会用到 python。

解决办法有两个：
1. 翻墙重新装，或者用 cnpm CLI 来安装，它会把二进制文件重定向到国内的 CDN。
2. 本地安装 Python 2.7 版本，将其加入 path 中之后，新开窗口重新安装。

**Comment by ccsulzf** [comment]
建议安装windows-build-tools先把环境搞好

**Comment by asnowwolf** [comment]
@heyrdaxm 题主如果解决了问题请来回复一下。

**Comment by zhangxinyong12** [comment]
node -v
v8.12.0
ng 6.0.8 
cnpm i
ng serve 之后一直卡住95% 必须要 用yarn i 才可以

**Comment by asnowwolf** [comment]
那个文件被墙了

**Comment by zhangxinyong12** [comment]
难道真的是python的原因。我yarn的时候提示我python不存在

**Comment by zhangxinyong12** [comment]
> 哦？卡住的那个点有什么提示？

没有提示，就是一直不动。等了1分钟，我就终止了，我用 yarn 可以

**Comment by zhangxinyong12** [comment]
> 问题解决了， 老老实实安装了phython 2.7的版本。
> 总结如下：网上看到很多说指定npm，Angular 版本的都不好用。 至于cnpm也没有多大的用处。
> 就是安装新版node.js 然后老老实实补装python，让他从源码编译即可。 知道真相的我眼泪掉下来。
刚装了python2.7 结果一样。卡在95%

**Comment by asnowwolf** [comment]
恩，先用 python 方式解决吧，非编译方式得另外想办法。回头出了方案我就更新上来。

**Comment by heyrdaxm** [comment]
> > 问题解决了， 老老实实安装了phython 2.7的版本。
> > 总结如下：网上看到很多说指定npm，Angular 版本的都不好用。 至于cnpm也没有多大的用处。
> > 就是安装新版node.js 然后老老实实补装python，让他从源码编译即可。 知道真相的我眼泪掉下来。
> > 刚装了python2.7 结果一样。卡在95%

这个坑之前我也踩过， 是用了cnpm install 将ng new  未完成的部分处理造成的，跟python那个是两个问题。建议卸载cnpm

**Comment by jiayisheji** [comment]
window装上 python2.7 不要其他版本，vs （版本随意），**注意**： 是vs不是vs code，ps: vs需要10g左右空间
 基本没有用问题，这组合我都用了几年，没有遇到node-sass问题，不推荐cnpm，网速不好还是弄个梯子吧

**Comment by YuiTH** [comment]
原来我每次yarn都在node-sass上卡好久就是因为他当场重新编译？yarn不是有本地cache功能么……连着跑两边都会卡好久。

**Comment by asnowwolf** [comment]
@YuiTH 这是因为它要从 aws 上下载一个二进制文件，当下载不了时，就会尝试从源码编译。而 aws 已经被墙了，所以在中国区无论用什么包管理工具，都只能从源码编译。

**Comment by wjx774326739** [comment]
安装node-sass也可以将这个的镜像地址换成国内的淘宝镜像：sass_binary_site=https://npm.taobao.org/mirrors/node-sass/

**Comment by cnscorpions** [comment]
换成淘宝镜像吧，py也装一下

**Comment by Caesar1226** [comment]
用yarn可以
